version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"   # Map container port 3000 to host port 3000
    volumes:
      - .:/usr/src/app  # Mount your local directory to the container for live reloads
      - /usr/src/app/node_modules  # Prevent overwriting node_modules
    environment:
      - NODE_ENV=development
    #restart: always